# Generated by Django 3.1.7 on 2021-03-26 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20210326_1602'),
    ]

    operations = [
        migrations.CreateModel(
            name='job_listing',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_title', models.CharField(blank=True, max_length=255, null=True)),
                ('job_description', models.TextField(blank=True, null=True)),
                ('job_url', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
    ]
