# Generated by Django 3.1.7 on 2021-03-26 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_job_listing'),
    ]

    operations = [
        migrations.RenameField(
            model_name='job_listing',
            old_name='job_url',
            new_name='company_name',
        ),
        migrations.AddField(
            model_name='job_listing',
            name='job_experience',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='job_listing',
            name='job_link',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='job_listing',
            name='job_location',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='job_listing',
            name='job_qualification',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='job_listing',
            name='job_requirements',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='job_listing',
            name='job_salary',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='job_listing',
            name='job_topic',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='job_listing',
            name='job_type',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
