# Generated by Django 3.1.7 on 2021-03-27 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_auto_20210327_0150'),
    ]

    operations = [
        migrations.CreateModel(
            name='JobListings',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('job_id', models.CharField(default='N/A', max_length=1000)),
                ('job_topic', models.CharField(default='N/A', max_length=1000)),
                ('company_name', models.CharField(default='N/A', max_length=100)),
                ('job_link', models.CharField(default='N/A', max_length=1000)),
                ('job_title', models.CharField(default='N/A', max_length=1000)),
                ('job_description', models.CharField(default='N/A', max_length=5000)),
                ('job_requirements', models.CharField(default='N/A', max_length=1000)),
                ('job_location', models.CharField(default='N/A', max_length=1000)),
                ('job_salary', models.CharField(default='N/A', max_length=1000)),
                ('job_qualification', models.CharField(default='N/A', max_length=1000)),
                ('job_type', models.CharField(default='N/A', max_length=1000)),
                ('job_experience', models.CharField(default='N/A', max_length=1000)),
            ],
        ),
        migrations.DeleteModel(
            name='job_listing',
        ),
    ]
