# Generated by Django 3.1.7 on 2021-03-27 07:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_tempmodel'),
        ('accounts', '0005_auto_20210327_1220'),
    ]

    operations = [
    ]
