# Generated by Django 3.1.7 on 2021-03-27 08:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_merge_20210327_1328'),
    ]

    operations = [
        migrations.CreateModel(
            name='InterviewQuestions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(blank=True, choices=[('General', 'General'), ('Marketing', 'Marketing'), ('Business', 'Business'), ('Tech', 'Tech')], max_length=255, null=True)),
                ('question_text', models.CharField(max_length=255)),
                ('recommended_answer', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='PracticeInterview',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video_upload', models.FileField(blank=True, null=True, upload_to='')),
                ('share_it', models.BooleanField(default=False)),
                ('question', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.interviewquestions')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='TempModel',
        ),
    ]
